upscale_cooldown=
upscale_target_metric=
upscale_metric_threshold=
upscale_evaluation_cycles=
upscale_evaluation_period=
upscale_comparison_operator=
upscale_statistic=

downscale_cooldown=
downscale_target_metric=
downscale_metric_threshold=
downscale_evaluation_cycles=
downscale_evaluation_period=
downscale_comparison_operator=
downscale_statistic=
